"""
Problem 2
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.


Answer:  4613732
"""

FibSeq = [1, 2]
Even_sum = 2

while (FibSeq[-1] + FibSeq[-2]) < 4000000:
    if (FibSeq[-1] + FibSeq[-2]) % 2 == 0:
        Even_sum = Even_sum + (FibSeq[-1] + FibSeq[-2])
    FibSeq.append(FibSeq[-1] + FibSeq[-2])

print(Even_sum)